//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PayrollSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonalDetail
    {
        public int EmployeeID { get; set; }
        public string GivenName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public short Age { get; set; }
        public System.DateTime BirthDate { get; set; }
        public string Contact { get; set; }
        public string Address { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
