//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PayrollSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Salary
    {
        public int SalaryID { get; set; }
        public int EmployeeID { get; set; }
        public decimal DailyRate { get; set; }
        public short WorkedDaysByMonth { get; set; }
        public decimal GrossSalary { get; set; }
        public decimal NetSalary { get; set; }
        public System.DateTime ForTheMonthOf { get; set; }
        public string PreparedBy { get; set; }
        public System.DateTime DatePrepared { get; set; }
        public bool Released { get; set; }
        public bool ActiveTransaction { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
